### ISSUE TITLE
[MANTRUN-72] getting java.lang.NoClassDefFoundError: org/apache/tools/ant/PropertyHelper

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-antrun-plugin#240]
**[Michael Mattox](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cunparis)** opened **[MANTRUN-72](https://issues.apache.org/jira/browse/MANTRUN-72?redirect=false)** and commented

when I try to build the servicemix examples, I get this error:

java.lang.NoClassDefFoundError: org/apache/tools/ant/PropertyHelper

I've searched and found that it was reported in maven 2.0.6 but supposedly works in < 2.0.6.  For me I get it all the time.  The other reports were with xdoclet, I'm not using xdoclet.  so I think there is a bigger issue.

full stack trave & pom attached

---

**Affects:** 1.1

**Attachments:**
- [jira1.txt](https://issues.apache.org/jira/secure/attachment/12713683/jira1.txt) (_19.47 kB_)
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12713668/pom.xml) (_4.95 kB_)

**Comment by jira-importer** [comment]
**[Michael Mattox](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cunparis)** commented

see http://jira.codehaus.org/browse/MNG-2917 and http://jira.codehaus.org/browse/MOJO-618

**Comment by jira-importer** [comment]
**[Michael Mattox](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cunparis)** commented

I'm closing the issue as it's not blocking me any more and there doesn't seem to be any interest.
